/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import static Ventanas.CambioDeContraseña.generarCadenaRandom;
import appregistroincidencias.ConexionDB;
import appregistroincidencias.Registro;
import appregistroincidencias.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import java.io.FileWriter;
import java.io.IOException;


/**
 *
 * @author USER
 */
public class Inicio extends javax.swing.JFrame {
    private Usuario usuarioEnUso;
    
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    private ArrayList<Registro> listaRegistro = new ArrayList<>();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();               
    }
    
    public Inicio(Usuario usuario) {
        initComponents();  
        usuarioEnUso = usuario;
        if ("Comun".equals(usuarioEnUso.getTipo())) {
            icon_editar.setVisible(false);
            icon_eliminar.setVisible(false);
            lbl_cuaEliminar.setVisible(false);
            lbl_cuaEditar.setVisible(false);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icon_registro = new javax.swing.JLabel();
        icon_eliminar = new javax.swing.JLabel();
        icon_ver = new javax.swing.JLabel();
        icon_editar = new javax.swing.JLabel();
        icon_generar = new javax.swing.JLabel();
        icon_perfil = new javax.swing.JLabel();
        lbl_resueltos = new javax.swing.JLabel();
        lbl_sinIniciar = new javax.swing.JLabel();
        lbl_proceso = new javax.swing.JLabel();
        lbl_cuaReporte = new javax.swing.JLabel();
        lbl_cuaEliminar = new javax.swing.JLabel();
        lbl_cuaVer = new javax.swing.JLabel();
        lbl_cuaEditar = new javax.swing.JLabel();
        lbl_cuaGenerar = new javax.swing.JLabel();
        lbl_recResueltos = new javax.swing.JLabel();
        lbl_recProceso = new javax.swing.JLabel();
        lbl_recSinIniciar = new javax.swing.JLabel();
        lbl_cirPerfil = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_listaMostrando = new javax.swing.JList<>();
        lbl_fondo2 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconRegistro.png"))); // NOI18N
        icon_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_registroMouseClicked(evt);
            }
        });
        jPanel1.add(icon_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 50, 50));

        icon_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconEliminar.png"))); // NOI18N
        icon_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_eliminarMouseClicked(evt);
            }
        });
        jPanel1.add(icon_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 50, 50));

        icon_ver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconVer.png"))); // NOI18N
        icon_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_verMouseClicked(evt);
            }
        });
        jPanel1.add(icon_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 50, 50));

        icon_editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconEditar.png"))); // NOI18N
        icon_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_editarMouseClicked(evt);
            }
        });
        jPanel1.add(icon_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 50, 50));

        icon_generar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconGenerar.png"))); // NOI18N
        icon_generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_generarMouseClicked(evt);
            }
        });
        jPanel1.add(icon_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, 50));

        icon_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconPerfil.png"))); // NOI18N
        icon_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_perfilMouseClicked(evt);
            }
        });
        jPanel1.add(icon_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        lbl_resueltos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_resueltos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_resueltos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_resueltos.setText("Resueltos");
        lbl_resueltos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_resueltosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_resueltosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_resueltosMouseExited(evt);
            }
        });
        jPanel1.add(lbl_resueltos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, 50));

        lbl_sinIniciar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_sinIniciar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sinIniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sinIniciar.setText("Sin Iniciar");
        lbl_sinIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sinIniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_sinIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_sinIniciarMouseExited(evt);
            }
        });
        jPanel1.add(lbl_sinIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 50));

        lbl_proceso.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_proceso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_proceso.setText("En Proceso");
        lbl_proceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_procesoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_procesoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_procesoMouseExited(evt);
            }
        });
        jPanel1.add(lbl_proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, 50));

        lbl_cuaReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        lbl_cuaEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        lbl_cuaVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        lbl_cuaEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        lbl_cuaGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        lbl_recResueltos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecEsquinaDerCeleste.png"))); // NOI18N
        jPanel1.add(lbl_recResueltos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        lbl_recProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecCentroCeleste.png"))); // NOI18N
        jPanel1.add(lbl_recProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, -1));

        lbl_recSinIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecEsquinaIzqCeleste.png"))); // NOI18N
        jPanel1.add(lbl_recSinIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lbl_cirPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CirCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cirPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lst_listaMostrando.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lst_listaMostrando.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lst_listaMostrando.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lst_listaMostrando);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 390, 210));

        lbl_fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo2.png"))); // NOI18N
        jPanel1.add(lbl_fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 460));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fondo.png"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_perfilMouseClicked
        Perfil perfil = new Perfil(usuarioEnUso, this);
        perfil.setLocationRelativeTo(this);
        perfil.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_icon_perfilMouseClicked

    private void icon_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_registroMouseClicked
        RegistroDeReporte ventRegistro = new RegistroDeReporte(usuarioEnUso, this);
        ventRegistro.setLocationRelativeTo(this);
        ventRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_icon_registroMouseClicked

    private void icon_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_editarMouseClicked
        int index = lst_listaMostrando.getSelectedIndex();
        Registro registro = listaRegistro.get(index);
        RegistroDeReporte ventRegistro = new RegistroDeReporte(usuarioEnUso,registro,this);
        ventRegistro.setLocationRelativeTo(this);
        ventRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_icon_editarMouseClicked

    private void icon_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_verMouseClicked
        int index = lst_listaMostrando.getSelectedIndex();
        Registro registro = listaRegistro.get(index);
        RegistroDeReporte ventRegistro = new RegistroDeReporte(registro,this);
        ventRegistro.setLocationRelativeTo(this);
        ventRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_icon_verMouseClicked

    private void icon_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_eliminarMouseClicked
        int index = lst_listaMostrando.getSelectedIndex();
        Registro registro = listaRegistro.get(index);        
        
        ConexionDB cx = new ConexionDB();             
        try {            
            String consulta = "delete from registros where id_registro = " + registro.getId_registro();
            Statement st = cx.conectar().createStatement();
            int filasAfectadas = st.executeUpdate(consulta);
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, 
                      "El registro SI ha sido eliminado en la DB");             
            } else {
                JOptionPane.showMessageDialog(this, 
                         "El registro NO ha sido eliminado en la DB");
            }            
        } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).
                        log(Level.SEVERE, null, ex);
        } 
        cx.desconectar(); 
        listaRegistro.remove(index);
        actualizarLista("Todos");            
    }//GEN-LAST:event_icon_eliminarMouseClicked

    private void lbl_sinIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sinIniciarMouseClicked
        actualizarLista("Sin iniciar");
    }//GEN-LAST:event_lbl_sinIniciarMouseClicked

    private void lbl_sinIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sinIniciarMouseEntered
        lbl_recSinIniciar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecEsquinaIzqCelesteO.png")));
    }//GEN-LAST:event_lbl_sinIniciarMouseEntered

    private void lbl_sinIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sinIniciarMouseExited
        lbl_recSinIniciar.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecEsquinaIzqCeleste.png")));
    }//GEN-LAST:event_lbl_sinIniciarMouseExited

    private void lbl_procesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_procesoMouseClicked
        actualizarLista("En proceso");
    }//GEN-LAST:event_lbl_procesoMouseClicked

    private void lbl_procesoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_procesoMouseEntered
        lbl_recProceso.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecCentroCelesteO.png")));
    }//GEN-LAST:event_lbl_procesoMouseEntered

    private void lbl_procesoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_procesoMouseExited
        lbl_recProceso.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecCentroCeleste.png")));
    }//GEN-LAST:event_lbl_procesoMouseExited

    private void lbl_resueltosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_resueltosMouseClicked
        actualizarLista("Resuelto");
    }//GEN-LAST:event_lbl_resueltosMouseClicked

    private void lbl_resueltosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_resueltosMouseEntered
        lbl_recResueltos.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecEsquinaDerCelesteO.png")));
    }//GEN-LAST:event_lbl_resueltosMouseEntered

    private void lbl_resueltosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_resueltosMouseExited
       lbl_recResueltos.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/Imgs/RecEsquinaDerCeleste.png")));
    }//GEN-LAST:event_lbl_resueltosMouseExited

    private void icon_generarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_generarMouseClicked
        int index = lst_listaMostrando.getSelectedIndex();
        Registro registro = listaRegistro.get(index);        
        
        if(registro != null){
            try {
                generarReporte(registro);
                JOptionPane.showMessageDialog(this, 
                        "El registro SI se pudo generar!!! " + "Revise su carpeta de descargas");
            } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(this, 
                        "El registro NO se pudo generar");
        }   
    }//GEN-LAST:event_icon_generarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    public void actualizarLista(String estado){
        listaRegistro.removeAll(listaRegistro);
        modeloLista.removeAllElements();
        lst_listaMostrando.removeAll();

        ConexionDB cx = new ConexionDB();
        try {
            String consulta;
            
            if ("Todos".equals(estado)) {
                consulta = "select * from registros";
            } else{
                consulta = "select * from registros where estado = '" + estado + "'";
            }
            
            Statement st = cx.conectar().createStatement();
            ResultSet rs = st.executeQuery(consulta);

            while (rs.next()) {
                Registro registro = new Registro();
                registro.setId_registro(rs.getInt("id_registro"));
                registro.setTitulo(rs.getString("titulo"));
                registro.setDescripcion(rs.getString("descripcion"));
                registro.setCategoria(rs.getString("categoria"));
                registro.setEstado(rs.getString("estado"));
                registro.setPrioridad(rs.getString("prioridad"));
                listaRegistro.add(registro);

                String modelo = registro.getId_registro() + "  " + registro.getTitulo();
                modeloLista.addElement(modelo);
            }

            if (listaRegistro.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay registros en la base de datos");
            } else {
                // Después de procesar todos los registros, asigna el modelo al JList
                lst_listaMostrando.setModel(modeloLista);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        cx.desconectar();
    }
    
    public void generarReporte(Registro registro) throws IOException{
        FileWriter fichero = new FileWriter("C:/Users/USER/Downloads/reporte.txt");

        // Añadir encabezado
        fichero.write("ID Registro | ID Usuario | Título | Descripción | Categoría | Estado | Prioridad\n");

        fichero.write(registro.getId_registro() + " | " + registro.
                getId_usuario() + " | " + registro.getTitulo() + " | " + 
                registro.getDescripcion() + " | " + registro.getCategoria() + 
                " | " + registro.getEstado() + " | " + registro.getPrioridad() 
                + "\n");

        // Cerrar el archivo
        fichero.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_editar;
    private javax.swing.JLabel icon_eliminar;
    private javax.swing.JLabel icon_generar;
    private javax.swing.JLabel icon_perfil;
    private javax.swing.JLabel icon_registro;
    private javax.swing.JLabel icon_ver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cirPerfil;
    private javax.swing.JLabel lbl_cuaEditar;
    private javax.swing.JLabel lbl_cuaEliminar;
    private javax.swing.JLabel lbl_cuaGenerar;
    private javax.swing.JLabel lbl_cuaReporte;
    private javax.swing.JLabel lbl_cuaVer;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_fondo2;
    private javax.swing.JLabel lbl_proceso;
    private javax.swing.JLabel lbl_recProceso;
    private javax.swing.JLabel lbl_recResueltos;
    private javax.swing.JLabel lbl_recSinIniciar;
    private javax.swing.JLabel lbl_resueltos;
    private javax.swing.JLabel lbl_sinIniciar;
    private javax.swing.JList<String> lst_listaMostrando;
    // End of variables declaration//GEN-END:variables
}
