/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author USER
 */
public class RegistroDeReporte extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public RegistroDeReporte() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        txt_involucrado = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        cb_estado = new javax.swing.JComboBox<>();
        cb_categoria = new javax.swing.JComboBox<>();
        cb_prioridad1 = new javax.swing.JComboBox<>();
        icon_guardar = new javax.swing.JLabel();
        icon_volver = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_tituloReporte = new javax.swing.JLabel();
        lbl_involucrado1 = new javax.swing.JLabel();
        lbl_involucrado = new javax.swing.JLabel();
        lbl_prioridad = new javax.swing.JLabel();
        lbl_categoria = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_cuaGuardar = new javax.swing.JLabel();
        lbl_cuaVolver = new javax.swing.JLabel();
        lbl_fondo2 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setWheelScrollingEnabled(false);

        txt_descripcion.setColumns(10);
        txt_descripcion.setLineWrap(true);
        txt_descripcion.setRows(5);
        txt_descripcion.setAutoscrolls(false);
        jScrollPane1.setViewportView(txt_descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 410, 100));

        txt_involucrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_involucrado.setForeground(new java.awt.Color(128, 173, 216));
        jPanel1.add(txt_involucrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 190, -1));

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(128, 173, 216));
        txt_titulo.setText("Titulo del registro...");
        jPanel1.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 410, 40));

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        jPanel1.add(cb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 90, -1));

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        jPanel1.add(cb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, -1));

        cb_prioridad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        jPanel1.add(cb_prioridad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 90, -1));

        icon_guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconGuardar.png"))); // NOI18N
        jPanel1.add(icon_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 50, 50));

        icon_volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconVolver.png"))); // NOI18N
        jPanel1.add(icon_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 50));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(128, 173, 216));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("REGISTRO DEL REPORTE");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 430, -1));

        lbl_tituloReporte.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_tituloReporte.setForeground(new java.awt.Color(149, 177, 246));
        lbl_tituloReporte.setText("Titulo");
        jPanel1.add(lbl_tituloReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 410, 36));

        lbl_involucrado1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_involucrado1.setForeground(new java.awt.Color(149, 177, 246));
        lbl_involucrado1.setText("Estado");
        jPanel1.add(lbl_involucrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 40));

        lbl_involucrado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_involucrado.setForeground(new java.awt.Color(149, 177, 246));
        lbl_involucrado.setText("Involucrado/s");
        jPanel1.add(lbl_involucrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 36));

        lbl_prioridad.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_prioridad.setForeground(new java.awt.Color(149, 177, 246));
        lbl_prioridad.setText("Prioridad");
        jPanel1.add(lbl_prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 90, 36));

        lbl_categoria.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_categoria.setForeground(new java.awt.Color(149, 177, 246));
        lbl_categoria.setText("Categoría");
        jPanel1.add(lbl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 36));

        lbl_descripcion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(149, 177, 246));
        lbl_descripcion.setText("Descripción");
        jPanel1.add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 410, 36));

        lbl_cuaGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        lbl_cuaVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_cuaVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lbl_fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo2.png"))); // NOI18N
        jPanel1.add(lbl_fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 460));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fondo.png"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_prioridad1;
    private javax.swing.JLabel icon_guardar;
    private javax.swing.JLabel icon_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_cuaGuardar;
    private javax.swing.JLabel lbl_cuaVolver;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_fondo2;
    private javax.swing.JLabel lbl_involucrado;
    private javax.swing.JLabel lbl_involucrado1;
    private javax.swing.JLabel lbl_prioridad;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_tituloReporte;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_involucrado;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
