/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import appregistroincidencias.ConexionDB;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author USER
 */
public class RegistroUsuario extends javax.swing.JFrame {
    
    private InicioSesion ventAnt;
    private VerUsuarios ventAnt2;
    private int cualVentana; // 1 = inicio de sesio, 2 = verUsuarios
    /**
     * Creates new form RegistoUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }
    
    public RegistroUsuario(InicioSesion ventAnt) {
        initComponents();
        this.ventAnt = ventAnt;
        cualVentana = 1;
    }
    
    public RegistroUsuario(VerUsuarios ventAnt) {
        initComponents();
        this.ventAnt2 = ventAnt;
        cualVentana = 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_volver = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        pw_contra = new javax.swing.JPasswordField();
        pw_confirmarContra = new javax.swing.JPasswordField();
        lbl_registrar = new javax.swing.JLabel();
        lbl_boton = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_fondo2 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_volver.setForeground(new java.awt.Color(193, 248, 255));
        lbl_volver.setText("Volver");
        lbl_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_volverMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        txt_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(128, 173, 216));
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 40));

        txt_correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(128, 173, 216));
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, 40));
        jPanel1.add(pw_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 290, 40));
        jPanel1.add(pw_confirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 290, 40));

        lbl_registrar.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lbl_registrar.setForeground(new java.awt.Color(193, 255, 248));
        lbl_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registrar.setText("REGISTRAR");
        lbl_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registrarMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 240, 50));

        lbl_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecCeleste.png"))); // NOI18N
        jPanel1.add(lbl_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(128, 173, 216));
        lbl_titulo.setText("REGISTRO");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        lbl_fondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo2.png"))); // NOI18N
        jPanel1.add(lbl_fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 400));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fondo.png"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registrarMouseClicked
        ConexionDB cx = new ConexionDB();
        try {            
            String usuario = txt_usuario.getText();
            String correo = txt_correo.getText();
            String contra = String.valueOf(pw_contra.getPassword());
            String confirContra = String.valueOf(pw_confirmarContra.getPassword());
            if (confirContra.equals(contra)) {
                String consulta = "insert into usuarios (usuario, contra, correo, tipo)" 
                    + "values ('" + usuario + "', '" + contra + "', '" + correo + "', 'Comun')";
                Statement st = cx.conectar().createStatement();
                int filasAfectadas = st.executeUpdate(consulta);
                if (filasAfectadas > 0) {
                    JOptionPane.showMessageDialog(this, 
                            "El usuario ha sido registrado en la DB");             
                } else {
                    JOptionPane.showMessageDialog(this, 
                            "El usuario NO se pudo registrar en la DB");
                }
            }else{
                JOptionPane.showMessageDialog(this, 
                            "¡Las contraseñas ingresadas no coinciden!"); 
            }                                  
        } catch (SQLException ex) {
            Logger.getLogger(InicioSesion.class.getName()).
                    log(Level.SEVERE, null, ex);
        } 
        cx.desconectar();
    }//GEN-LAST:event_lbl_registrarMouseClicked

    private void lbl_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_volverMouseClicked
        //InicioSesion ventanaAnterior = new InicioSesion();
        if (cualVentana == 1) {
            ventAnt.setLocationRelativeTo(this);
            ventAnt.setVisible(true);        
            this.setVisible(false);  
        } else if (cualVentana == 2){      
            ventAnt2.actualizarLista();
            ventAnt2.setLocationRelativeTo(this);
            ventAnt2.setVisible(true);        
            this.setVisible(false);  
        }
    }//GEN-LAST:event_lbl_volverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_boton;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_fondo2;
    private javax.swing.JLabel lbl_registrar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_volver;
    private javax.swing.JPasswordField pw_confirmarContra;
    private javax.swing.JPasswordField pw_contra;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
